### ISSUE TITLE
Script stopped working (Chrome, Firefox, Opera)

### ISSUE THREAD

**Issue by Sithlord512589** [sumaeq/cb-chat-utils#1]
Hi, i´ve been using you script for a while now but somehow it´s seems to be broken.
I´ve tried it in Opera, Firefox and maily used in Chrome with Tampermonkey stable and beta..
It worked perfectly for a few weeks but recently only the auto tipper is working.
The chat filters don´t work..
I´m honest.. I´m not a programmer i´m a user with knowledge in program languages nobody knows today.
So i would kindle ask you of you could update that script or tell me a work around to get it running.
Thanks in advance...
If it is a simple adaptation that i can learn to handle myself...
I would be glad to hear the solution.

**Comment by sumaeq** [comment]
Thanks @Sithlord512589 for pointing this out! I just pushed v0.5.0 out, it should fix the issue. Chaturbate had only changed the ID of the chat window to be its class name instead!

**Comment by Sithlord512589** [comment]
Wow, thank you very much for your quick response.. I tested it and you fixed it...
Man. you saved my life... I´m a mod and your tool helps me a lot to follow the "real" chat.
May i ask for a feature? or two?
First is it possible to get that time stamp on PM chats (on/off) too?
Second is possible to save or export a chat (main/PM)?
Don´t get me wrong i´m very thankful you fixed it... I´m just asking.
